### ISSUE TITLE
Stuck at "Hero Heroku is loading...."

### ISSUE THREAD

**Issue by omidshojaee** [TheBrenny/hero-heroku#1]
Extension version: v1.2.0
VSCode Version: 1.58.2

**Comment by TheBrenny** [comment]
Hey! Can you provide some more detail on how this happened? Can you confirm you've entered an API key into the `hero-heroku.apiKey` setting?

**Comment by omidshojaee** [comment]
Yes the API key is entered. 

I click on the extension icon and that message appears indefinitely.

**Comment by TheBrenny** [comment]
Interesting. Are you able to dump your ~~Extension Host~~ Hero Heroku logs to a [gist](gist.github.com)? ~~Feel free to remove everything except the hero-heroku logs.~~

---

Edit: I think I see what you mean... It was just stuck on that message for about 15 minutes, but I think it has something to do with other extensions taking their time to load. I'm going to keep investigating this, though.

**Comment by omidshojaee** [comment]
Here's the gist:
https://gist.github.com/omidshojaee/00c9d06fb37c609e168f84501ccd3dc8

**Comment by TheBrenny** [comment]
Thanks for that, and sorry for getting back so late.

Are you able to dump your Hero Heroku logs as well?

And is the loading bar still spinning underneath the Hero Heroku title or is it stopped?

**Comment by TheBrenny** [comment]
Bump @omidshojaee. Is this still an issue that you're facing?

**Comment by TheBrenny** [comment]
Closing due to lack of inactivity.

**Comment by TheBrenny** [comment]
I was working on a friends computer and did a fresh install of this extension and came across this error. It looked like it _tried_ to refresh the tree, but the spinner wasn't actually there, and it actually wasn't doing anything. I'm not sure where this happened, but I'm guessing somewhere it didn't actually trigger the refresh.

I'll look into this a little bit more and report back what I find.

(PS, this is starting to become more of a diary entry for this particular issue! No need to reply if! 😅)

**Comment by TheBrenny** [comment]
Note: this should be fixed with the HDP rewrite (`v1.6.0`).
