### ISSUE TITLE
[FEATURE REQUEST] Use Hero Heroku to view and edit remote files

### ISSUE THREAD

**Issue by windmillcode0** [TheBrenny/hero-heroku#2]
I would like the ability to read/write to files via vscode extension by leveraging heroku run bash

**Comment by TheBrenny** [comment]
Hey! Can you give more of an explanation on what you mean?

**Comment by windmillcode0** [comment]
I believe we requested that we can edit the fiiles in heroku environment, however I believe files running there are ephermeral, so if there is an update to sqlite file I believe we wont be able to access it

**Comment by TheBrenny** [comment]
Unfortunately, the filesystem is indeed ephemeral, but this doesn't mean the data can't be changed. For example, you can remote in and use nano, vi, or whatever is installed to modify the files.

But I do understand the intention to being able to at least view the remote files (maybe there's a config file, or a generated log file or something which you might want to get access to).

I'll keep this open, but I won't be able to action it for a while.

**Comment by windmillcode0** [comment]
Much appreciated hopefully we can take a look at electron courses and then be able to help you out

**Comment by TheBrenny** [comment]
Hey, sorry for taking 5 months to respond! I've come back to this, re-read the comments and I'm probably going to say that I don't plan on implementing this. An alternative (like I mentioned) would be to SSH into the dyno (using the button available) and then inspecting/modifying the filesystem that way. The only problem you face then, is that each dyno has a unique fs, and that modifying one dyno will not propagate to the other dynos.
